# Generated by Django 2.2.1 on 2019-05-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='elev_cour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=200, unique=True)),
                ('nom_cour', models.CharField(max_length=200)),
                ('nom_elev', models.CharField(max_length=200)),
                ('explication', models.CharField(max_length=40000)),
            ],
        ),
        migrations.CreateModel(
            name='prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(null=True)),
                ('nom_du_cours', models.CharField(max_length=200)),
                ('nom_prof', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('explication', models.CharField(max_length=200)),
                ('profs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questi.prof')),
            ],
        ),
        migrations.CreateModel(
            name='user_elev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(null=True)),
                ('score_champ', models.IntegerField(null=True)),
                ('question', models.CharField(max_length=40000)),
                ('rep_tru', models.IntegerField()),
                ('s_cour_elevs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questi.elev_cour')),
                ('s_elevs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questi.user_elev')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(null=True)),
                ('nom_du_cours', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.CharField(max_length=40000)),
                ('rep_tru', models.CharField(max_length=40000)),
                ('rep_1', models.CharField(max_length=40000)),
                ('rep_2', models.CharField(max_length=40000)),
                ('rep_3', models.CharField(max_length=40000)),
                ('rep_4', models.CharField(max_length=40000)),
                ('questionnaires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questi.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='elev_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(null=True)),
                ('nom_du_cours', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.CharField(max_length=40000)),
                ('rep_t', models.BooleanField(default=False)),
                ('rep_f', models.BooleanField(default=False)),
                ('rep_t_2', models.BooleanField(default=False)),
                ('rep_t_3', models.BooleanField(default=False)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questi.elev_cour')),
            ],
        ),
        migrations.AddField(
            model_name='elev_cour',
            name='user_elevs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questi.user_elev'),
        ),
    ]
