# Generated by Django 2.2.1 on 2019-05-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='rep_tru_id',
            field=models.IntegerField(null=True),
        ),
    ]
