# Generated by Django 2.2.1 on 2019-06-16 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='proff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
