# Generated by Django 2.2.1 on 2019-06-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0002_auto_20190616_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='proff',
            new_name='user',
        ),
    ]
