# Generated by Django 2.2.1 on 2019-06-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0003_auto_20190616_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='anne',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profil',
            name='les_classe',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
