# Generated by Django 2.2.1 on 2019-06-16 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0004_auto_20190617_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='profil',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='questi.Profil'),
        ),
    ]
