# Generated by Django 2.2.1 on 2019-06-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0006_prof_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='profil',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
