# Generated by Django 2.2.1 on 2019-06-17 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0008_user_elev_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_classe', models.CharField(max_length=200)),
                ('name_prof', models.ManyToManyField(default=False, to='questi.prof')),
            ],
        ),
        migrations.CreateModel(
            name='cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cour', models.CharField(max_length=200)),
                ('name_classe', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='questi.classe')),
            ],
        ),
        migrations.RemoveField(
            model_name='elev_question',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='profs',
        ),
        migrations.RemoveField(
            model_name='score',
            name='s_cour_elevs',
        ),
        migrations.AlterField(
            model_name='questions',
            name='questionnaires',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='questi.questionnaire'),
        ),
        migrations.AlterField(
            model_name='score',
            name='s_elevs',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='questi.user_elev'),
        ),
        migrations.DeleteModel(
            name='elev_cour',
        ),
        migrations.DeleteModel(
            name='elev_question',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='cours',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='questi.cours'),
        ),
        migrations.AddField(
            model_name='user_elev',
            name='name_classe',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='questi.classe'),
        ),
    ]
