# Generated by Django 2.2.1 on 2019-06-18 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0009_auto_20190617_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='s_prof',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='questi.prof'),
        ),
    ]
