# Generated by Django 2.2.1 on 2019-06-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0011_auto_20190619_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
