# Generated by Django 2.2.1 on 2019-06-19 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0012_classe_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='count',
        ),
    ]
