# Generated by Django 2.2.1 on 2019-06-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0013_remove_classe_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='name_prof',
        ),
        migrations.AddField(
            model_name='prof',
            name='name_classe',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='questi.classe'),
        ),
    ]
