# Generated by Django 2.2.1 on 2019-06-19 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0015_cours_name_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='name_prof',
        ),
    ]
