# Generated by Django 2.2.1 on 2019-06-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0017_cours_name_prof'),
    ]

    operations = [
        migrations.CreateModel(
            name='prof_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='questi.classe')),
                ('proff', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='questi.prof')),
            ],
        ),
    ]
