# Generated by Django 2.2.1 on 2019-06-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0018_prof_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quest',
            field=models.CharField(max_length=40000, verbose_name='la question'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='rep_1',
            field=models.CharField(max_length=40000, verbose_name='reponse 1'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='rep_2',
            field=models.CharField(max_length=40000, verbose_name='reponse 2'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='rep_3',
            field=models.CharField(max_length=40000, verbose_name='reponse 3'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='rep_4',
            field=models.CharField(max_length=40000, verbose_name='reponse 4'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='rep_tru_id',
            field=models.IntegerField(null=True, verbose_name='indiquer le numero de la reponse juste'),
        ),
    ]
