# Generated by Django 2.2.1 on 2019-06-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questi', '0020_score_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='classe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questi.classe'),
        ),
    ]
